FROM debian:stretch

RUN apt-get update
RUN apt-get upgrade -y

RUN apt-get install -y curl openssh-server pdsh

COPY config/.ssh /root/.ssh
RUN chmod 700 /root/.ssh

RUN apt-get install -y openjdk-8-jdk
ENV JAVA_HOME /usr/lib/jvm/java-8-openjdk-amd64

RUN curl http://ftp.jaist.ac.jp/pub/apache/hadoop/common/hadoop-3.0.0-alpha4/hadoop-3.0.0-alpha4.tar.gz | tar xzf - -C /opt
ENV HADOOP_HOME /opt/hadoop-3.0.0-alpha4

RUN sed -i 's!^export JAVA_HOME=${JAVA_HOME}$!export JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64!g' ${HADOOP_HOME}/etc/hadoop/hadoop-env.sh

COPY config/hadoop ${HADOOP_HOME}

COPY entrypoints/hadoop /entrypoints
ENTRYPOINT ["/entrypoints/hadoop-default.sh"]

RUN touch /entrypoints/first-run

# ssh
EXPOSE 22
# hadoop
EXPOSE 8000-65535
