FROM debian:stretch


RUN apt-get update
RUN apt-get upgrade -y


RUN apt-get install -y curl openssh-server pdsh


ARG authorized_keys
ARG config
ARG id_rsa
ARG id_rsa_pub

COPY ${authorized_keys} /root/.ssh/authorized_keys
COPY ${config} /root/.ssh/config
COPY ${id_rsa} /root/.ssh/id_rsa
COPY ${id_rsa_pub} /root/.ssh/id_rsa.pub

RUN chmod 700 /root/.ssh
RUN chmod 600 /root/.ssh/authorized_keys
RUN chmod 600 /root/.ssh/config
RUN chmod 600 /root/.ssh/id_rsa
RUN chmod 644 /root/.ssh/id_rsa.pub

RUN service ssh restart


RUN apt-get install -y openjdk-8-jdk
ENV JAVA_HOME /usr/lib/jvm/java-8-openjdk-amd64
ENV PATH ${PATH}:${JAVA_HOME}/bin:${JAVA_HOME}/sbin


RUN curl http://ftp.jaist.ac.jp/pub/apache/hadoop/common/hadoop-2.7.3/hadoop-2.7.3.tar.gz | tar xzf - -C /opt
ENV HADOOP_HOME /opt/hadoop-2.7.3
ENV PATH ${PATH}:${HADOOP_HOME}/bin:${HADOOP_HOME}/sbin

RUN sed -i 's!^export JAVA_HOME=${JAVA_HOME}$!export JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64!g' ${HADOOP_HOME}/etc/hadoop/hadoop-env.sh

COPY hadoop/core-site.xml ${HADOOP_HOME}/etc/hadoop/core-site.xml
COPY hadoop/hdfs-site.xml ${HADOOP_HOME}/etc/hadoop/hdfs-site.xml
COPY hadoop/mapred-site.xml ${HADOOP_HOME}/etc/hadoop/mapred-site.xml
COPY hadoop/yarn-site.xml ${HADOOP_HOME}/etc/hadoop/yarn-site.xml

RUN hdfs namenode -format


COPY hadoop/docker-entrypoint.sh /usr/local/bin/
ENTRYPOINT ["docker-entrypoint.sh"]

EXPOSE 22
EXPOSE 2122
EXPOSE 8020 8030 8031 8032 8033 8040 8042 8088
EXPOSE 9000
EXPOSE 10020 19888
EXPOSE 49707
EXPOSE 50010 50020 50070 50075 50090

