version: '3'

services:
  hadoop:
    build:
      context: .
      dockerfile: dockerfile-hadoop
      args:
        authorized_keys: .ssh/authorized_keys
        config: .ssh/config
        id_rsa: .ssh/hadoop.id_rsa
        id_rsa_pub: .ssh/hadoop.id_rsa.pub
    expose:
      - '22'
    ports:
      - '8020:8020'
      - '9000:9000'
      - '50010:50010'
      - '50020:50020'
      - '50070:50070'
      - '50075:50075'
      - '50090:50090'
      - '10020:10020'
      - '19888:19888'
      - '8030:8030'
      - '8031:8031'
      - '8032:8032'
      - '8033:8033'
      - '8040:8040'
      - '8042:8042'
      - '8088:8088'
      - '49707:49707'
      - '2122:2122'
      
  hbase:
    build:
      context: .
      dockerfile: dockerfile-hbase
      args:
        authorized_keys: .ssh/authorized_keys
        config: .ssh/config
        id_rsa: .ssh/hbase.id_rsa
        id_rsa_pub: .ssh/hbase.id_rsa.pub
    expose:
      - '22'
    ports:
      - '16010:16010'
      - '16012:16012'
      - '16013:16013'
      - '16015:16015'
      - '16020:16020'
      - '16022:16022'
      - '16023:16023'
      - '16025:16025'
      - '16030:16030'
      - '16032:16032'
      - '16033:16033'
      - '16035:16035'
      - '16200:16200'
      - '16202:16202'
      - '16300:16300'
      - '16302:16302'
    depends_on:
      - hadoop

